server:
  port: "50051"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "siwuai"
  parseTime: true

etcd:
  endpoints:
    - "localhost:2379"
  serviceName: "siwuai"
  serviceAddr: "127.0.0.1:50051"
  ttl: 5
