// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: vector.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []string               `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"` // 要生成向量的内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorRequest) Reset() {
	*x = GetVectorRequest{}
	mi := &file_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorRequest) ProtoMessage() {}

func (x *GetVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorRequest.ProtoReflect.Descriptor instead.
func (*GetVectorRequest) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{0}
}

func (x *GetVectorRequest) GetContent() []string {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []*VectorData          `protobuf:"bytes,1,rep,name=vector,proto3" json:"vector,omitempty"` // 二维float数组字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorResponse) Reset() {
	*x = GetVectorResponse{}
	mi := &file_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorResponse) ProtoMessage() {}

func (x *GetVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorResponse.ProtoReflect.Descriptor instead.
func (*GetVectorResponse) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{1}
}

func (x *GetVectorResponse) GetVector() []*VectorData {
	if x != nil {
		return x.Vector
	}
	return nil
}

type VectorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"` // 每个向量维度的值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorData) Reset() {
	*x = VectorData{}
	mi := &file_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorData) ProtoMessage() {}

func (x *VectorData) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorData.ProtoReflect.Descriptor instead.
func (*VectorData) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{2}
}

func (x *VectorData) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_vector_proto protoreflect.FileDescriptor

const file_vector_proto_rawDesc = "" +
	"\n" +
	"\fvector.proto\x12\x06vector\",\n" +
	"\x10GetVectorRequest\x12\x18\n" +
	"\acontent\x18\x01 \x03(\tR\acontent\"?\n" +
	"\x11GetVectorResponse\x12*\n" +
	"\x06vector\x18\x01 \x03(\v2\x12.vector.VectorDataR\x06vector\"$\n" +
	"\n" +
	"VectorData\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values2Q\n" +
	"\rvectorService\x12@\n" +
	"\tGetVector\x12\x18.vector.GetVectorRequest\x1a\x19.vector.GetVectorResponseB\x04Z\x02./b\x06proto3"

var (
	file_vector_proto_rawDescOnce sync.Once
	file_vector_proto_rawDescData []byte
)

func file_vector_proto_rawDescGZIP() []byte {
	file_vector_proto_rawDescOnce.Do(func() {
		file_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)))
	})
	return file_vector_proto_rawDescData
}

var file_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vector_proto_goTypes = []any{
	(*GetVectorRequest)(nil),  // 0: vector.GetVectorRequest
	(*GetVectorResponse)(nil), // 1: vector.GetVectorResponse
	(*VectorData)(nil),        // 2: vector.VectorData
}
var file_vector_proto_depIdxs = []int32{
	2, // 0: vector.GetVectorResponse.vector:type_name -> vector.VectorData
	0, // 1: vector.vectorService.GetVector:input_type -> vector.GetVectorRequest
	1, // 2: vector.vectorService.GetVector:output_type -> vector.GetVectorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vector_proto_init() }
func file_vector_proto_init() {
	if File_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_proto_goTypes,
		DependencyIndexes: file_vector_proto_depIdxs,
		MessageInfos:      file_vector_proto_msgTypes,
	}.Build()
	File_vector_proto = out.File
	file_vector_proto_goTypes = nil
	file_vector_proto_depIdxs = nil
}
