server:
  port: "50051"

mysql:
  host: "8.154.36.180"
  port: 8901
  username: "root"
  password: "lezhiedu@2024"
  dbname: "siwuai"

redis:
  addr: "8.154.36.180:8902"
  password: "lezhiedu@2024"
  db: 0
  timeout: 5

etcd:
  endpoints:
    - "8.154.36.180:2378"
  serviceName: "/services/siwuai"
  serviceAddr: "8.154.36.180:50051"
  ttl: 5

token:
  secretKey: "123456"
  generateTokenKey: "123456"

log:
  logPath: "./logs"
  appName: "siwuai"
  level: 0

llm:
  apiKey: "18e25f60-6aff-418f-96fe-55b8cee6a273"
  model: "deepseek-r1-250120"
  baseURL: "https://ark.cn-beijing.volces.com/api/v3"
  temperatureCode: 0.0
  temperatureArticle: 1.0

embedding:
  apiKey: "18e25f60-6aff-418f-96fe-55b8cee6a273"
  model: "doubao-embedding-text-240715"
  baseURL: "https://ark.cn-beijing.volces.com/api/v3"