server:
  port: ""

mysql:
  host: ""
  port: 
  username: ""
  password: ""
  dbname: ""

redis:
  addr: ""
  password: ""
  db: 0
  timeout: 5

etcd:
  endpoints:
    - ""
  serviceName: ""
  serviceAddr: ""
  ttl: 5

token:
  secretKey: ""
  generateTokenKey: ""

log:
  logPath: ""
  appName: ""
  level: 0

llm:
  apiKey: ""
  model: ""
  baseURL: ""
  temperatureCode: 0.0
  temperatureArticle: 1.0

embedding:
  apiKey: ""
  model: ""
  baseURL: "https://ark.cn-beijing.volces.com/api/v3"
