// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: question.proto

package question

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 生成标题的请求参数
type GenerateQuestionTitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`        // 问题的完整内容（必填）
	QuestionID    uint32                 `protobuf:"varint,2,opt,name=questionID,proto3" json:"questionID,omitempty"` // 问题ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionTitlesRequest) Reset() {
	*x = GenerateQuestionTitlesRequest{}
	mi := &file_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionTitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionTitlesRequest) ProtoMessage() {}

func (x *GenerateQuestionTitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionTitlesRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionTitlesRequest) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQuestionTitlesRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateQuestionTitlesRequest) GetQuestionID() uint32 {
	if x != nil {
		return x.QuestionID
	}
	return 0
}

// 生成标题的响应结果
type GenerateQuestionTitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`       // 哈希值（用于唯一标识本次生成任务）
	Titles        []string               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"` // 生成的标题列表（至少返回1个）
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`  // 生成的标题总数（与 titles 长度一致）
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // 生成状态（如 "success"/"failed"）
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`     // 问题关联的标签（可选，用于优化生成效果）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionTitlesResponse) Reset() {
	*x = GenerateQuestionTitlesResponse{}
	mi := &file_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionTitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionTitlesResponse) ProtoMessage() {}

func (x *GenerateQuestionTitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionTitlesResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionTitlesResponse) Descriptor() ([]byte, []int) {
	return file_question_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQuestionTitlesResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateQuestionTitlesResponse) GetTitles() []string {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *GenerateQuestionTitlesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GenerateQuestionTitlesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateQuestionTitlesResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_question_proto protoreflect.FileDescriptor

const file_question_proto_rawDesc = "" +
	"\n" +
	"\x0equestion.proto\x12\bquestion\"Y\n" +
	"\x1dGenerateQuestionTitlesRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"questionID\x18\x02 \x01(\rR\n" +
	"questionID\"\x8c\x01\n" +
	"\x1eGenerateQuestionTitlesResponse\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x16\n" +
	"\x06titles\x18\x02 \x03(\tR\x06titles\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags2~\n" +
	"\x0fQuestionService\x12k\n" +
	"\x16GenerateQuestionTitles\x12'.question.GenerateQuestionTitlesRequest\x1a(.question.GenerateQuestionTitlesResponseB\x17Z\x15siwuai/proto/questionb\x06proto3"

var (
	file_question_proto_rawDescOnce sync.Once
	file_question_proto_rawDescData []byte
)

func file_question_proto_rawDescGZIP() []byte {
	file_question_proto_rawDescOnce.Do(func() {
		file_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)))
	})
	return file_question_proto_rawDescData
}

var file_question_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_question_proto_goTypes = []any{
	(*GenerateQuestionTitlesRequest)(nil),  // 0: question.GenerateQuestionTitlesRequest
	(*GenerateQuestionTitlesResponse)(nil), // 1: question.GenerateQuestionTitlesResponse
}
var file_question_proto_depIdxs = []int32{
	0, // 0: question.QuestionService.GenerateQuestionTitles:input_type -> question.GenerateQuestionTitlesRequest
	1, // 1: question.QuestionService.GenerateQuestionTitles:output_type -> question.GenerateQuestionTitlesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_question_proto_init() }
func file_question_proto_init() {
	if File_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_question_proto_rawDesc), len(file_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_question_proto_goTypes,
		DependencyIndexes: file_question_proto_depIdxs,
		MessageInfos:      file_question_proto_msgTypes,
	}.Build()
	File_question_proto = out.File
	file_question_proto_goTypes = nil
	file_question_proto_depIdxs = nil
}
